# Generated by Django 4.2.7 on 2024-01-13 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='date',
            new_name='created_date',
        ),
    ]
